#!/usr/bin/env node
// Regenerates docs/browse.md from data/citations.csv.
//
// Why this exists: GitHub renders a CSV as a table with no text wrapping and no
// column width control, so long prose columns push everything off screen. A
// markdown table does wrap, so this produces a narrow reading view of the same
// data. The CSV stays the source of truth; this file is derived and should
// never be edited by hand.
//
// Run with --check to fail if the file is out of date. CI does that.

import { readFileSync, writeFileSync } from 'node:fs';

const SRC = 'data/citations.csv';
const OUT = 'docs/browse.md';

function parseCsv(text) {
  const rows = [];
  let row = [], field = '', inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') { if (text[i + 1] === '"') { field += '"'; i++; } else inQuotes = false; }
      else field += c;
    } else if (c === '"') inQuotes = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else if (c !== '\r') field += c;
  }
  if (field !== '' || row.length) { row.push(field); rows.push(row); }
  return rows.filter(r => r.length > 1 || r[0] !== '');
}

const rows = parseCsv(readFileSync(SRC, 'utf8'));
const head = rows.shift();
const col = Object.fromEntries(head.map((h, i) => [h, i]));
const cell = (r, name) => (r[col[name]] ?? '').trim();
const esc = (s) => s.replace(/\|/g, '\\|');

const DIRECTION = {
  'supports': 'supports',
  'does-not-support': '**does not support**',
  'mixed': 'mixed',
  'null-result': '**found nothing**',
  'background': 'background',
};

const byNutrient = new Map();
for (const r of rows) {
  const n = cell(r, 'nutrient');
  if (!byNutrient.has(n)) byNutrient.set(n, []);
  byNutrient.get(n).push(r);
}

const lines = [];
lines.push('# Browse the citations');
lines.push('');
lines.push('A reading view of [the citation data](../data/citations.csv), grouped by nutrient.');
lines.push('');
lines.push('This page is generated from the data file and wraps to fit a screen, which the raw');
lines.push('data view does not. Use the data file to sort and search, and this page to read.');
lines.push('');
lines.push(`${rows.length} entries. Do not edit this file by hand; it is rebuilt from the data.`);
lines.push('');
lines.push('**What the columns mean.** "What it says" is the contributor\'s one-sentence summary.');
lines.push('"Finding" is whether the paper supports the claim, fails to support it, or found nothing.');
lines.push('"Strength" is the reviewer\'s grade of how good the evidence is.');
lines.push('');

for (const [nutrient, items] of [...byNutrient.entries()].sort()) {
  lines.push(`## ${nutrient} (${items.length})`);
  lines.push('');
  lines.push('| # | What it says | Finding | Strength | Source |');
  lines.push('|---|---|---|---|---|');
  for (const r of items.sort((a, b) => Number(cell(a, 'id')) - Number(cell(b, 'id')))) {
    const pmid = cell(r, 'pmid');
    const doi = cell(r, 'doi');
    const year = cell(r, 'year');
    const link = pmid
      ? `[${year}](https://pubmed.ncbi.nlm.nih.gov/${pmid}/)`
      : doi ? `[${year}](https://doi.org/${doi})` : year;
    const design = cell(r, 'study_design').replace(/-/g, ' ');
    lines.push(`| ${cell(r, 'id')} | ${esc(cell(r, 'headline_phrase'))} | ${DIRECTION[cell(r, 'direction')] ?? cell(r, 'direction')} | ${cell(r, 'evidence_grade') || 'ungraded'} | ${link}, ${design} |`);
  }
  lines.push('');
}

const out = lines.join('\n');

if (process.argv.includes('--check')) {
  let current = '';
  try { current = readFileSync(OUT, 'utf8'); } catch {}
  if (current !== out) {
    console.error(`\n${OUT} is out of date. Run: node scripts/build-browse.mjs\n`);
    process.exit(1);
  }
  console.log(`\n${OUT} is up to date.\n`);
} else {
  writeFileSync(OUT, out);
  console.log(`\n${OUT} rebuilt: ${rows.length} entries across ${byNutrient.size} nutrients.\n`);
}
